# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/find_replace.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindReplaceWindow(object):
    def setupUi(self, FindReplaceWindow):
        FindReplaceWindow.setObjectName("FindReplaceWindow")
        FindReplaceWindow.resize(556, 307)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FindReplaceWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(FindReplaceWindow)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(FindReplaceWindow)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(FindReplaceWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(FindReplaceWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(FindReplaceWindow)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(FindReplaceWindow)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(FindReplaceWindow)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_2)

        self.retranslateUi(FindReplaceWindow)
        #self.pushButton_3.clicked.connect(FindReplaceWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FindReplaceWindow)
        FindReplaceWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        FindReplaceWindow.setTabOrder(self.lineEdit_2, self.pushButton)
        FindReplaceWindow.setTabOrder(self.pushButton, self.pushButton_2)
        FindReplaceWindow.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, FindReplaceWindow):
        _translate = QtCore.QCoreApplication.translate
        FindReplaceWindow.setWindowTitle(_translate("FindReplaceWindow", "Find and Replace"))
        self.label.setText(_translate("FindReplaceWindow", "F&ind:"))
        self.label_2.setText(_translate("FindReplaceWindow", "Re&place:"))
        self.pushButton.setText(_translate("FindReplaceWindow", "&Find"))
        self.pushButton_2.setText(_translate("FindReplaceWindow", "&Replace"))
        self.pushButton_3.setText(_translate("FindReplaceWindow", "&Cancel"))
